//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language is {0}.
        /// </summary>
        internal static string ChangeCultureCommand_CurrentLanguage {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ChangeCultureCommand_English {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ChangeCultureCommand_Language {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ChangeCultureCommand_Russian {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string GoogleSearchCommand_Google {
            get {
                return ResourceManager.GetString("GoogleSearchCommand_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string HelloCommand_Hello {
            get {
                return ResourceManager.GetString("HelloCommand_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string MathCommand_Plus {
            get {
                return ResourceManager.GetString("MathCommand_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string ReadTextCommand_Read {
            get {
                return ResourceManager.GetString("ReadTextCommand_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up.
        /// </summary>
        internal static string ShutUpCommand_ShutUp {
            get {
                return ResourceManager.GetString("ShutUpCommand_ShutUp", resourceCulture);
            }
        }
    }
}
