//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language is {0}.
        /// </summary>
        internal static string ChangeCultureCommand_CurrentLanguage {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ChangeCultureCommand_English {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ChangeCultureCommand_Language {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ChangeCultureCommand_Russian {
            get {
                return ResourceManager.GetString("ChangeCultureCommand_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string GoogleSearchCommand_Google {
            get {
                return ResourceManager.GetString("GoogleSearchCommand_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string HelloCommand_Hello {
            get {
                return ResourceManager.GetString("HelloCommand_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string MathCommand_Plus {
            get {
                return ResourceManager.GetString("MathCommand_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string MouseAdapterCommand_Click {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease step.
        /// </summary>
        internal static string MouseAdapterCommand_DecreaseStep {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_DecreaseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click.
        /// </summary>
        internal static string MouseAdapterCommand_DoubleClick {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string MouseAdapterCommand_Hold {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase step.
        /// </summary>
        internal static string MouseAdapterCommand_IncreaseStep {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_IncreaseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse adapter is turned off.
        /// </summary>
        internal static string MouseAdapterCommand_MouseAdapterIsTurnedOff {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MouseAdapterIsTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse adapter is turned on.
        /// </summary>
        internal static string MouseAdapterCommand_MouseAdapterIsTurnedOn {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MouseAdapterIsTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string MouseAdapterCommand_MoveDown {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string MouseAdapterCommand_MoveLeft {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string MouseAdapterCommand_MoveRight {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string MouseAdapterCommand_MoveUp {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string MouseAdapterCommand_Release {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step is maximal.
        /// </summary>
        internal static string MouseAdapterCommand_StepIsMaximal {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_StepIsMaximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step is minimal.
        /// </summary>
        internal static string MouseAdapterCommand_StepIsMinimal {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_StepIsMinimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off mouse adapter.
        /// </summary>
        internal static string MouseAdapterCommand_TurnOffMouseAdapter {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_TurnOffMouseAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on mouse adapter.
        /// </summary>
        internal static string MouseAdapterCommand_TurnOnMouseAdapter {
            get {
                return ResourceManager.GetString("MouseAdapterCommand_TurnOnMouseAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My computer.
        /// </summary>
        internal static string OpenPathCommand_MyComputer {
            get {
                return ResourceManager.GetString("OpenPathCommand_MyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenPathCommand_Open {
            get {
                return ResourceManager.GetString("OpenPathCommand_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string ReadTextCommand_Read {
            get {
                return ResourceManager.GetString("ReadTextCommand_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up.
        /// </summary>
        internal static string ShutUpCommand_ShutUp {
            get {
                return ResourceManager.GetString("ShutUpCommand_ShutUp", resourceCulture);
            }
        }
    }
}
