//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language is {0}.
        /// </summary>
        internal static string ChangeCultureModule_CurrentLanguage {
            get {
                return ResourceManager.GetString("ChangeCultureModule_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ChangeCultureModule_English {
            get {
                return ResourceManager.GetString("ChangeCultureModule_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ChangeCultureModule_Language {
            get {
                return ResourceManager.GetString("ChangeCultureModule_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ChangeCultureModule_Russian {
            get {
                return ResourceManager.GetString("ChangeCultureModule_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string GoogleSearchModule_Google {
            get {
                return ResourceManager.GetString("GoogleSearchModule_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string HelloModule_Hello {
            get {
                return ResourceManager.GetString("HelloModule_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string MathModule_Plus {
            get {
                return ResourceManager.GetString("MathModule_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string MouseAdapterModule_Click {
            get {
                return ResourceManager.GetString("MouseAdapterModule_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease step.
        /// </summary>
        internal static string MouseAdapterModule_DecreaseStep {
            get {
                return ResourceManager.GetString("MouseAdapterModule_DecreaseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click.
        /// </summary>
        internal static string MouseAdapterModule_DoubleClick {
            get {
                return ResourceManager.GetString("MouseAdapterModule_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string MouseAdapterModule_Hold {
            get {
                return ResourceManager.GetString("MouseAdapterModule_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase step.
        /// </summary>
        internal static string MouseAdapterModule_IncreaseStep {
            get {
                return ResourceManager.GetString("MouseAdapterModule_IncreaseStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse adapter is turned off.
        /// </summary>
        internal static string MouseAdapterModule_MouseAdapterIsTurnedOff {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MouseAdapterIsTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse adapter is turned on.
        /// </summary>
        internal static string MouseAdapterModule_MouseAdapterIsTurnedOn {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MouseAdapterIsTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string MouseAdapterModule_MoveDown {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string MouseAdapterModule_MoveLeft {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string MouseAdapterModule_MoveRight {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string MouseAdapterModule_MoveUp {
            get {
                return ResourceManager.GetString("MouseAdapterModule_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string MouseAdapterModule_Release {
            get {
                return ResourceManager.GetString("MouseAdapterModule_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step is maximal.
        /// </summary>
        internal static string MouseAdapterModule_StepIsMaximal {
            get {
                return ResourceManager.GetString("MouseAdapterModule_StepIsMaximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step is minimal.
        /// </summary>
        internal static string MouseAdapterModule_StepIsMinimal {
            get {
                return ResourceManager.GetString("MouseAdapterModule_StepIsMinimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off mouse adapter.
        /// </summary>
        internal static string MouseAdapterModule_TurnOffMouseAdapter {
            get {
                return ResourceManager.GetString("MouseAdapterModule_TurnOffMouseAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on mouse adapter.
        /// </summary>
        internal static string MouseAdapterModule_TurnOnMouseAdapter {
            get {
                return ResourceManager.GetString("MouseAdapterModule_TurnOnMouseAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My computer.
        /// </summary>
        internal static string OpenPathModule_MyComputer {
            get {
                return ResourceManager.GetString("OpenPathModule_MyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenPathModule_Open {
            get {
                return ResourceManager.GetString("OpenPathModule_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string ReadTextModule_Read {
            get {
                return ResourceManager.GetString("ReadTextModule_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up.
        /// </summary>
        internal static string ShutUpModule_ShutUp {
            get {
                return ResourceManager.GetString("ShutUpModule_ShutUp", resourceCulture);
            }
        }
    }
}
